#!/bin/bash

echo "=== Canary Management Commands ==="

echo ""
echo "1. Update to Green version (v2):"
echo "   kubectl argo rollouts set image canary-demo web-app=belo:green"
echo ""
echo "2. Watch rollout progress:"
echo "   kubectl argo rollouts get rollout canary-demo -w"
echo ""
echo "3. Promote to next step:"
echo "   kubectl argo rollouts promote canary-demo"
echo ""
echo "4. Abort rollout:"
echo "   kubectl argo rollouts abort canary-demo"
echo ""
echo "5. Retry rollout:"
echo "   kubectl argo rollouts retry canary-demo"
echo ""
echo "6. Get rollout status:"
echo "   kubectl argo rollouts get rollout canary-demo"
echo ""
echo "7. Access application:"
echo "   kubectl port-forward svc/canary-service 8080:80"
echo "   Then visit: http://localhost:8080"